### ISSUE TITLE
Self-Hosted LLM?

### ISSUE THREAD

**Issue by vsecv** [fuzz4all/fuzz4all#1]
Hello,

Is there a way to configure it in an on-premise environment?

Looking at the contents, I think need external API(Ex) GPT).

Is there a way to test in an environment where I can't communicate with the outside world?

I'm looking for a way to fuzz without exposing the data (source code) to the outside.

Thanks

**Comment by brutalsavage** [comment]
Hi,

You definitely do not need to use GPT if you want to use Fuzz4All, one way is to supply your own prompts. 
To do this you can adjust the configuration file accordingly, as an example please see: https://github.com/fuzz4all/fuzz4all/blob/13ecb201170a4e80fead9d936e9bf927072e1027/config/ablation/c_std_documentation.yaml

In this example, we have `use_hand_written_prompt: true` which indicates that we want to use the handwritten input in the `path_documentation` configuration (in the example it is `path_documentation: config/documentation/c/c_std.md`).
This will tell Fuzz4All we want to forgo autoprompting (i.e., using GPT-4) and directly use the handwritten prompt

You can of course also modify Fuzz4All to use another local/self-hosted LLM to do the autoprompting, which requires a bit of work :)

**Comment by vsecv** [comment]
@brutalsavage Thank you for your reply. I will try to refer to the information you sent me! Have a happy day
