### ISSUE TITLE
Library support?

### ISSUE THREAD

**Issue by vsecv** [fuzz4all/fuzz4all#2]
Hello,

It appears that there are mainly examples for compiled languages.

Is it possible to do fuzzing for general-purpose libraries as well?

For example, libcurl, libpcap

Thanks.

**Comment by brutalsavage** [comment]
Yes it is definitely possible, as long as these libraries take in some inputs which can be of some file format containing semantically meaningful strings. You can setup these libraries similar to how you may setup the existing targets and feed them generated fuzzing inputs from Fuzz4All to perform fuzzing.

**Comment by vsecv** [comment]
@brutalsavage  Thank you for your reply. Let's try it!
