### ISSUE TITLE
Enquiry about canonical document distillation

### ISSUE THREAD

**Issue by Mount4in** [fuzz4all/fuzz4all#4]
1. Reading through your code, I found that Fuzz4ALL reads the document from config/documentation/xx/xx.md and stores it to dict_compat[‘docstring’], but no reference to dict_compat[‘docstring’] was found during prompting LLM.

2. Also, I would like to ask you how you handle document input that exceeds the maximum window limit of LLM?

**Comment by brutalsavage** [comment]
Hi,

> Reading through your code, I found that Fuzz4ALL reads the document from config/documentation/xx/xx.md and stores it to dict_compat[‘docstring’], but no reference to dict_compat[‘docstring’] was found during prompting LLM.

you can see docstring used in these lines to create the initial input to the LLM:
https://github.com/fuzz4all/fuzz4all/blob/13ecb201170a4e80fead9d936e9bf927072e1027/Fuzz4All/target/target.py#L254-L259 

>Also, I would like to ask you how you handle document input that exceeds the maximum window limit of LLM?

Yes currently there is no special considering to documents which exceeds the maximum token limit of LLMs, however if you use GPT-4 for example, the context window is actually quite large. But you are right that this could definitely be an issue, you may choose to truncate some of the documents in case it runs out

**Comment by Mount4in** [comment]
Thanks!
