### ISSUE TITLE
Do you find bugs using differential testing?

### ISSUE THREAD

**Issue by Strke** [fuzz4all/fuzz4all#6]
This is my first time working on this topic, so I don't really know how to find bugs in the object under test.

I've read some similar papers recently, and found that in CSmith, he used the same program to run and compare different versions of the compiler to find errors. Do you do the same?

**Comment by brutalsavage** [comment]
Differential testing is definitely one way of finding bugs, in our paper we usually focus on more simple oracles like crashes (which should not happen) to find bugs. But you can definitely set up differential testing oracles for example on different compiler versions or even different compilers (e.g., clang vs gcc) and then check for differences in their outputs when given a fuzzing input.

**Comment by Strke** [comment]
Okay, thank you！
