### ISSUE TITLE
No matching distribution found for genhtml

### ISSUE THREAD

**Issue by Fs2qFtoS** [fuzz4all/fuzz4all#7]
Hi, I have created a conda virtual environment as requested, but in requirements.txt there is a module called genhtml。
I tried with `pip install genhtml`
ERROR: Could not find a version that satisfies the requirement genhtml (from versions: none)
ERROR: No matching distribution found for genhtml

**Comment by brutalsavage** [comment]
Hi thanks for raising this issue, it seems that genhtml pypi package has been depreciated, but this package is actually not needed to run Fuzz4All (only as a wrapper to collect coverage), I have removed it from the requirements. Please try again with the new repo

**Comment by Fs2qFtoS** [comment]
Ok, thanks for that.
